# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procheckapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsinfo',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
